Iter25
dnsoftware/go-metrics pull request #25
Opened 2024-06-04 14:29 UTC by dnsoftware

2024-06-06 15:55 UTC, Bazys requested changes
1. goimports
2. prealloc

и все не по одному разу

2024-06-06 15:55 UTC, Bazys commented on internal/server/handlers/grpc.go
> +	var temp []Metrics
Преаллоцируй слайс. Тебе известен его будущий размер. как то так:
```go
temp := make([]Metrics, 0, len(in.Metrics))
```
Таки образом повышаем производительность Go-приложения за счет минимизации динамического выделения памяти во время выполнения. Предварительное аллоцирование слайсов в Go может значительно сократить накладные расходы на увеличение слайса по мере добавления элементов, что предполагает выделение новой памяти и копирование существующих элементов в новое пространство памяти.
В Go, когда вы заранее знаете количество элементов, которые будет вмещать слайс, вы можете использовать функцию `make`, чтобы указать его начальную длину и объем. Такая практика особенно полезна для слайсов, размер которых увеличивается по мере выполнения программы, поскольку избавляет Go от необходимости автоматически изменять размер слайса каждый раз, когда в него добавляется элемент после превышения его емкости.
Предварительное аллокация выгодна для производительности, особенно в сценариях с большими массивами данных или высокопроизводительными задачами, потому что она уменьшает количество выделений памяти и связанные с этим затраты на управление памятью, например сборку мусора.
Для более подробного тзучения оптимизации производительности кода Go и управления памятью, включая эффективное использование срезов и функции `make`, посмотри на таких ресурсам, как:
1. [The Impact of Preallocating Slice Memory in Golang (Continued)](https://oilbeater.com/en/2024/03/04/golang-slice-performance-cont/)
2. [Optimize by pre-allocating slice](https://www.programming-books.io/essential/go/optimize-by-pre-allocating-slice-ee6501b596c9446da8b82e4ed35454a6)

2024-06-06 15:55 UTC, Bazys commented on internal/server/handlers/grpc.go
> +	_ "google.golang.org/grpc/encoding/gzip" // для активации декомпрессора
импорты не сгруппированы

2024-06-08 08:35 UTC, dnsoftware commented on internal/server/handlers/grpc.go
> +	_ "google.golang.org/grpc/encoding/gzip" // для активации декомпрессора
у меня goimports почему-то не убирает пустые строки между импортами

2024-06-10 11:00 UTC, Bazys commented on internal/server/handlers/grpc.go
> +	_ "google.golang.org/grpc/encoding/gzip" // для активации декомпрессора
а это группировка. првило простое
1. std lib
2. github и иные публичные репы
3. импорт из твоего проекта

2024-06-10 11:49 UTC, merged